@startuml
UserInterface -> writer : generateCarte(Mesh carte)
writer --> Traductor : CreateCarte(Mesh carte)
Traductor --> map : new map(Mesh carte)
Traductor <-- map : map carte
writer <-- Traductor : map carte
writer --> map : enrich()
writer <-- map : map enrichCarte
writer --> Traductor : CreateMesh(map enrichCarte)
writer <-- Traductor : enrichMesh
UserInterface <-- writer : enrichMesh


@enduml