@startuml

package UserInterface {
    class UserInterface {
        - CommandLine configure(String[] args)
    }
}
Package writer {
    class writer {
        + LegacyMesh generateCarte(String : type)
    }
}
Package Traductor {
    class Traductor{
        + map createCarte()
    }
}
Package Legacy {
    class LegacyMesh
    class LegacyPolygon
    class LegacyPoint
    class LegacySegment

}

Package CarteGenerator {
     Interface Carte1 {
        + int : hauteur
        + int : largeur
        + String : type
        + map enrich(map carte)
        - map genShape(type)
     }

     class map {
         + int : hauteur
         + int : largeur
         + String : type
         + map enrich(map carte)
         - map genShape(type)

     }
     class Tuile {
         Point: centre
         Tuile[] : voisin
         Segment[] : frontiere
     }
     class Point {
        int : X
        int : Y
     }
     class Segment {
        Point : A
        Point : B
     }

     Interface Biome {
        String : nom
        String : color
        String : property
     }
}

Carte1 <-- map
writer -- UserInterface
writer -- Traductor
writer -- map
Traductor --|> Legacy
Traductor --|> map
map "1" *-- "*" Tuile
Tuile "*" -- "1" Biome
Tuile "2" *-- "*" Segment
Tuile "1" --* "1" Point
Point "2" *-- "*" Segment

@enduml