@startuml
UserInterface -> writer : generateCarte(Mesh world)
writer --> Traductor : CreateCarte(Mesh world)
Traductor --> world : new world(Mesh world)
Traductor <-- world : world world
writer <-- Traductor : world world
writer --> world : enrich()
writer <-- world : world enrichCarte
writer --> Traductor : CreateMesh(world enrichCarte)
writer <-- Traductor : enrichMesh
UserInterface <-- writer : enrichMesh


@enduml